### ISSUE TITLE
편집 저장시 가끔 문제가 생김

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#283]
"변경사항 저장"을 눌렀을 때
- 편집은 저장되지만 500이 떴던 것 같으며,
- 해당 편집이 바뀐글에 표시되지 않습니다(즉 DB의 recentchanges 테이블에 추가되지 않습니다)

```
NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to MessageCache::isMainCacheable() must be of the type array, null given, called in /srv/femiwiki.com/includes/cache/MessageCache.php on line 1054 and defined in /srv/femiwiki.com/includes/cache/MessageCache.php:579
Stack trace:
#0 /srv/femiwiki.com/includes/cache/MessageCache.php(1054): MessageCache->isMainCacheable('internalerror', NULL)
#1 /srv/femiwiki.com/includes/cache/MessageCache.php(958): MessageCache->getMsgFromNamespace('Internalerror', 'ko')
#2 /srv/femiwiki.com/includes/cache/MessageCache.php(928): MessageCache->getMessageForLang(Object(Language), 'internalerror', true, Array)
#3 /srv/femiwiki.com/includes/cache/MessageCache.php(870): MessageCache->getMessageFromFallbackChain(Object(Language), 'internalerror', true)
#4 /srv/femiwiki.com/includes/Message.php(1299): MessageCache->get('internalerror', true, Object(Language))
#5 /srv/femiwiki.com/includes/Message.php(851): Message->fetchMessage()
#6 /srv/femiwiki.com/inc...
```

위는 비슷한 시간대의 도커 서비스 로그입니다.

발생 시기 상 https://www.mediawiki.org/wiki/Extension:DiscordNotifications 확장기능과 관련해 생긴 문제로 생각됩니다.

**Comment by lens0021** [comment]
```
[20-Jul-2019 05:21:40] WARNING: [pool www] child 96 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to MessageCache::isMainCacheable() must be of the type array, null given, called in /srv/femiwiki.com/includes/cache/MessageCache.php on line 1054 and defined in /srv/femiwiki.com/includes/cache/MessageCache.php:579"
[20-Jul-2019 05:21:40] WARNING: [pool www] child 96 said into stderr: "Stack trace:"
[20-Jul-2019 05:21:40] WARNING: [pool www] child 96 said into stderr: "#0 /srv/femiwiki.com/includes/cache/MessageCache.php(1054): MessageCache->isMainCacheable('internalerror', NULL)"
[20-Jul-2019 05:21:40] WARNING: [pool www] child 96 said into stderr: "#1 /srv/femiwiki.com/includes/cache/MessageCache.php(958): MessageCache->getMsgFromNamespace('Internalerror', 'ko')"
[20-Jul-2019 05:21:40] WARNING: [pool www] child 96 said into stderr: "#2 /srv/femiwiki.com/includes/cache/MessageCache.php(928): MessageCache->getMessageForLang(Object(Language), 'internalerror', true, Array)"
[20-Jul-2019 05:21:40] WARNING: [pool www] child 96 said into stderr: "#3 /srv/femiwiki.com/includes/cache/MessageCache.php(870): MessageCache->getMessageFromFallbackChain(Object(Language), 'internalerror', true)"
[20-Jul-2019 05:21:40] WARNING: [pool www] child 96 said into stderr: "#4 /srv/femiwiki.com/includes/Message.php(1299): MessageCache->get('internalerror', true, Object(Language))"
[20-Jul-2019 05:21:40] WARNING: [pool www] child 96 said into stderr: "#5 /srv/femiwiki.com/includes/Message.php(851): Message->fetchMessage()"
[20-Jul-2019 05:21:40] WARNING: [pool www] child 96 said into stderr: "#6 /srv/femiwiki.com/inc..."

```

**Comment by lens0021** [comment]
미디어위키:Vector.css에 대한 수정을 저장하려던 중에 500 에러를 보았고 로그입니다:
```
[exception] [6ffa0f990031cbe5215dd21a] /index.php?title=%EB%AF%B8%EB%94%94%EC%96%B4%EC%9C%84%ED%82%A4:Vector.css&action=submit   TypeError from line 579 of /srv/femiwiki.com/includes/cache/MessageCache.php: Argument 2 passed to MessageCache::isMainCacheable() must be of the type array, null given, called in /srv/femiwiki.com/includes/cache/MessageCache.php on line 1054
[exception] [6ffa0f990031cbe5215dd21a] /index.php?title=%EB%AF%B8%EB%94%94%EC%96%B4%EC%9C%84%ED%82%A4:Vector.css&action=submit   TypeError from line 579 of /srv/femiwiki.com/includes/cache/MessageCache.php: Argument 2 passed to MessageCache::isMainCacheable() must be of the type array, null given, called in /srv/femiwiki.com/includes/cache/MessageCache.php on line 1054
[fatal] [6ffa0f990031cbe5215dd21a] /index.php?title=%EB%AF%B8%EB%94%94%EC%96%B4%EC%9C%84%ED%82%A4:Vector.css&action=submit   PHP Fatal Error from line 579 of /srv/femiwiki.com/includes/cache/MessageCache.php: Uncaught TypeError: Argument 2 passed to MessageCache::isMainCacheable() must be of the type array, null given, called in /srv/femiwiki.com/includes/cache/MessageCache.php on line 1054 and defined in /srv/femiwiki.com/includes/cache/MessageCache.php:579
Stack trace:
#0 /srv/femiwiki.com/includes/cache/MessageCache.php(1054): MessageCache->isMainCacheable('internalerror', NULL)
#1 /srv/femiwiki.com/includes/cache/MessageCache.php(958): MessageCache->getMsgFromNamespace('Internalerror', 'ko')
#2 /srv/femiwiki.com/includes/cache/MessageCache.php(928): MessageCache->getMessageForLang(Object(Language), 'internalerror', true, Array)
#3 /srv/femiwiki.com/includes/cache/MessageCache.php(870): MessageCache->getMessageFromFallbackChain(Object(Language), 'internalerror', true)
#4 /srv/femiwiki.com/includes/Message.php(1299): MessageCache->get('internalerror', true, Object(Language))
#5 /srv/femiwiki.com/includes/Message.php(851): Message->fetchMessage()
#6 /srv/femiwiki.com/includes/Message.php(943): Message->toString('
```
마지막에 `Message->toString('`는 진짜 저기서 끝겼습니다.
덧붙여 `internalerror`는 [같은 이름의 시스템 메시지](https://femiwiki.com/w/%EB%AF%B8%EB%94%94%EC%96%B4%EC%9C%84%ED%82%A4:Internalerror) 같습니다.

**Comment by lens0021** [comment]
개발환경에서 이것저것 시험하기로 다음 에러가 발생하여
```
[error] [db27d4051819d967d1a26bed] /index.php?title=%EB%AF%B8%EB%94%94%EC%96%B4%EC%9C%84%ED%82%A4:Vector.css&action=submit   ErrorException from line 1079 of /srv/femiwiki.com/includes/cache/MessageCache.php: PHP Notice: Undefined index: ko
#0 /srv/femiwiki.com/includes/cache/MessageCache.php(1079): MWExceptionHandler::handleError(integer, string, string, integer, array)
#1 /srv/femiwiki.com/includes/cache/MessageCache.php(958): MessageCache->getMsgFromNamespace(string, string)
#2 /srv/femiwiki.com/includes/cache/MessageCache.php(928): MessageCache->getMessageForLang(Language, string, boolean, array)
#3 /srv/femiwiki.com/includes/cache/MessageCache.php(870): MessageCache->getMessageFromFallbackChain(Language, string, boolean)
#4 /srv/femiwiki.com/includes/Message.php(1299): MessageCache->get(string, boolean, Language)
#5 /srv/femiwiki.com/includes/Message.php(851): Message->fetchMessage()
#6 /srv/femiwiki.com/includes/Message.php(943): Message->toString(string)
#7 /srv/femiwiki.com/extensions/DiscordNotifications/DiscordNotificationsCore.php(564): Message->text()
#8 /srv/femiwiki.com/extensions/DiscordNotifications/DiscordNotificationsCore.php(143): DiscordNotifications::getMessage(string)
#9 /srv/femiwiki.com/includes/Hooks.php(174): DiscordNotifications::discord_article_saved(WikiPage, User, CssContent, string, integer, NULL, NULL, integer, Revision, Status, boolean, integer)
#10 /srv/femiwiki.com/includes/Hooks.php(202): Hooks::callHook(string, array, array, NULL)
#11 /srv/femiwiki.com/includes/Storage/PageUpdater.php(1214): Hooks::run(string, array)
#12 /srv/femiwiki.com/includes/libs/rdbms/database/Database.php(3815): MediaWiki\Storage\PageUpdater->MediaWiki\Storage\{closure}(Wikimedia\Rdbms\DatabaseMysqli, string)
#13 /srv/femiwiki.com/includes/libs/rdbms/database/DBConnRef.php(49): Wikimedia\Rdbms\Database->doAtomicSection(string, Closure)
#14 /srv/femiwiki.com/includes/libs/rdbms/database/DBConnRef.php(538): Wikimedia\Rdbms\DBConnRef->__call(string, array)
#15 /srv/femiwiki.com/includes/deferred/AtomicSectionUpdate.php(35): Wikimedia\Rdbms\DBConnRef->doAtomicSection(string, Closure)
#16 /srv/femiwiki.com/includes/deferred/DeferredUpdates.php(270): AtomicSectionUpdate->doUpdate()
#17 /srv/femiwiki.com/includes/deferred/DeferredUpdates.php(216): DeferredUpdates::runUpdate(AtomicSectionUpdate, Wikimedia\Rdbms\LBFactorySimple, string, integer)
#18 /srv/femiwiki.com/includes/deferred/DeferredUpdates.php(136): DeferredUpdates::execute(array, string, integer)
#19 /srv/femiwiki.com/includes/MediaWiki.php(599): DeferredUpdates::doUpdates(string, integer)
#20 /srv/femiwiki.com/includes/MediaWiki.php(568): MediaWiki::preOutputCommit(RequestContext, Closure)
#21 /srv/femiwiki.com/includes/MediaWiki.php(876): MediaWiki->doPreOutputCommit(Closure)
#22 /srv/femiwiki.com/includes/MediaWiki.php(517): MediaWiki->main()
#23 /srv/femiwiki.com/index.php(42): MediaWiki->run()
#24 {main}
```
https://github.com/femiwiki/DiscordNotifications 에 `ko` 브랜치를 만들고 ko.json 파일을 생성했습니다(https://github.com/femiwiki/DiscordNotifications/commit/2c01cdd325f3b08ef62824f3b4598de14db25053). 효과가 있을지는 잘 모르겠습니다.

**Comment by lens0021** [comment]
현재는 문제가 해결됐는지 안 됐는지를 확인하기 위해 지켜보는 상태이며, 오랫동안 문제가 발생하지 않으면 이 이슈를 닫으면 되겠습니다.

**Comment by lens0021** [comment]
https://femiwiki.com/index.php?diff=149845 편집 중 발생했습니다.

```
[11-Sep-2019 05:13:12] WARNING: [pool www] child 28342 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to MessageCache::isMainCacheable() must be of the type array, null given, called in /srv/femiwiki.com/includes/cache/MessageCache.php on line 1054 and defined in /srv/femiwiki.com/includes/cache/MessageCache.php:579"
[11-Sep-2019 05:13:12] WARNING: [pool www] child 28342 said into stderr: "Stack trace:"
[11-Sep-2019 05:13:12] WARNING: [pool www] child 28342 said into stderr: "#0 /srv/femiwiki.com/includes/cache/MessageCache.php(1054): MessageCache->isMainCacheable('internalerror', NULL)"
[11-Sep-2019 05:13:12] WARNING: [pool www] child 28342 said into stderr: "#1 /srv/femiwiki.com/includes/cache/MessageCache.php(958): MessageCache->getMsgFromNamespace('Internalerror', 'ko')"
[11-Sep-2019 05:13:12] WARNING: [pool www] child 28342 said into stderr: "#2 /srv/femiwiki.com/includes/cache/MessageCache.php(928): MessageCache->getMessageForLang(Object(Language), 'internalerror', true, Array)"
[11-Sep-2019 05:13:12] WARNING: [pool www] child 28342 said into stderr: "#3 /srv/femiwiki.com/includes/cache/MessageCache.php(870): MessageCache->getMessageFromFallbackChain(Object(Language), 'internalerror', true)"
[11-Sep-2019 05:13:12] WARNING: [pool www] child 28342 said into stderr: "#4 /srv/femiwiki.com/includes/Message.php(1299): MessageCache->get('internalerror', true, Object(Language))"
[11-Sep-2019 05:13:12] WARNING: [pool www] child 28342 said into stderr: "#5 /srv/femiwiki.com/includes/Message.php(851): Message->fetchMessage()"
[11-Sep-2019 05:13:12] WARNING: [pool www] child 28342 said into stderr: "#6 /srv/femiwiki.com/inc..."
```

**Comment by lens0021** [comment]
https://femiwiki.com/index.php?diff=150789 편집 중 발생했습니다.

**Comment by lens0021** [comment]
발생하지 않는 것 같아 보입니다.
