### ISSUE TITLE
Translate 확장기능 REL1_34 패치 적용

### ISSUE THREAD

**Issue by lens0021** [femiwiki/docker-mediawiki#328]
[https://femiwiki.com/index.php?title=Special:Translate
 &group=page-페미위키:대문
&language=en
&action=page
&filter=%21translated](https://femiwiki.com/index.php?title=Special:Translate&group=page-%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4%3A%EB%8C%80%EB%AC%B8&language=en&action=page&filter=%21translated)

```
Caught exception of type InvalidArgumentException
```

**Comment by lens0021** [comment]
프로덕션 서버의 로그입니다:
```
[exception] [e4dfd912e1665511e989360f] /api.php?action=query&format=json&list=messagecollection&mcgroup=page-%ED%8E%98%EB%AF%B8%EC%9C%84%ED%82%A4%3A%EB%8C%80%EB%AC%B8&mclanguage=ko&mclimit=100&mcfilter=!ignored%7C!optional&mcprop=definition%7Ctranslation%7Ctags%7Cproperties&rawcontinue=1&errorformat=html   InvalidArgumentException from line 2715 of /srv/femiwiki.com/includes/Revision/RevisionStore.php: text table can no longer be joined directly
#0 /srv/femiwiki.com/includes/Revision.php(316): MediaWiki\Revision\RevisionStore->getQueryInfo(array)
#1 /srv/femiwiki.com/extensions/Translate/MessageCollection.php(694): Revision::getQueryInfo(array)
#2 /srv/femiwiki.com/extensions/Translate/MessageCollection.php(244): MessageCollection->loadData(array)
#3 /srv/femiwiki.com/extensions/Translate/api/ApiQueryMessageCollection.php(127): MessageCollection->loadTranslations()
#4 /srv/femiwiki.com/extensions/Translate/api/ApiQueryMessageCollection.php(22): ApiQueryMessageCollection->run()
#5 /srv/femiwiki.com/includes/api/ApiQuery.php(255): ApiQueryMessageCollection->execute()
#6 /srv/femiwiki.com/includes/api/ApiMain.php(1598): ApiQuery->execute()
#7 /srv/femiwiki.com/includes/api/ApiMain.php(537): ApiMain->executeAction()
#8 /srv/femiwiki.com/includes/api/ApiMain.php(508): ApiMain->executeActionWithErrorHandling()
#9 /srv/femiwiki.com/api.php(87): ApiMain->execute()
#10 {main}
```

로컬에서 새 문서를 번역 대상으로 표시 후 번역하기를 눌렀을 때 나온 로그입니다:
```
[exception] [6de2c34cfbc23190f587d10b] /api.php?action=query&format=json&list=messagecollection&mcgroup=page-%EB%8C%80%EB%AC%B8&mclanguage=ko&mclimit=100&mcfilter=!ignored%7C!optional&mcprop=definition%7Ctranslation%7Ctags%7Cproperties&rawcontinue=1&errorformat=html   InvalidArgumentException from line 2715 of /srv/femiwiki.com/includes/Revision/RevisionStore.php: text table can no longer be joined directly
#0 /srv/femiwiki.com/includes/Revision.php(316): MediaWiki\Revision\RevisionStore->getQueryInfo(array)
#1 /srv/femiwiki.com/extensions/Translate/MessageCollection.php(694): Revision::getQueryInfo(array)
#2 /srv/femiwiki.com/extensions/Translate/MessageCollection.php(244): MessageCollection->loadData(array)
#3 /srv/femiwiki.com/extensions/Translate/api/ApiQueryMessageCollection.php(127): MessageCollection->loadTranslations()
#4 /srv/femiwiki.com/extensions/Translate/api/ApiQueryMessageCollection.php(22): ApiQueryMessageCollection->run()
#5 /srv/femiwiki.com/includes/api/ApiQuery.php(255): ApiQueryMessageCollection->execute()
#6 /srv/femiwiki.com/includes/api/ApiMain.php(1598): ApiQuery->execute()
#7 /srv/femiwiki.com/includes/api/ApiMain.php(537): ApiMain->executeAction()
#8 /srv/femiwiki.com/includes/api/ApiMain.php(508): ApiMain->executeActionWithErrorHandling()
#9 /srv/femiwiki.com/api.php(87): ApiMain->execute()
#10 {main}
```

**Comment by lens0021** [comment]
개발환경에서 테스트한 결과로 REL1_34에서는 에러가 나지만 [537483](https://gerrit.wikimedia.org/r/c/mediawiki/extensions/Translate/+/537483)([github](https://github.com/wikimedia/mediawiki-extensions-Translate/commit/4c3ad6f87)) 이후부터는 괜찮아 보입니다.

**Comment by lens0021** [comment]
해당 커밋 업스트림 REL1_34에 체리픽킹되었습니다: https://github.com/wikimedia/mediawiki-extensions-Translate/commit/0e726be
